language: dart

dart:
  - stable

# Only building develop means that we don't run two builds for each pull request.
branches:
  only: [develop]

dart_task:
  - dartfmt
  # - dartanalyzer

script:
  - cd package
  - pub get
  - pub run test_coverage
  - cp coverage/lcov.info ../../contentful_dart.lcov

after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
