language: dart

dart:
  - stable

dart_task:
  - dartfmt
  # - dartanalyzer

before_script:
  - pub global activate coverage

script:
  - dart test/all.dart

# script: ./scripts/runTests.sh
# after_success: bash <(curl -s https://codecov.io/bash) -f lcov.info

# Only building develop means that we don't run two builds for each pull request.
branches:
  only: [develop]

cache:
  directories:
    - $HOME/.pub-cache
