language: dart

dart:
  - stable

dart_task:
  - dartfmt
  - dartanalyzer

# Only building develop means that we don't run two builds for each pull request.
branches:
  only: [develop]

cache:
  directories:
    - $HOME/.pub-cache
