language: dart

dart:
  - dev
  - 2.4.0

dart_task:
  - dartanalyzer: --fatal-infos --fatal-warnings .

matrix:
  include:
    # Only validate formatting using the dev release
    - dart: develop
      dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [develop]

cache:
  directories:
    - $HOME/.pub-cache
