include: package:pedantic/analysis_options.yaml

analyzer:
  # exclude:
  #   - '**/*.g.dart'
  errors:
    missing_required_param: error
    always_put_required_named_parameters_first: error
    no_duplicate_case_values: error
    avoid_relative_lib_imports: error

linter:
  rules:
    - always_declare_return_types
    - avoid_catches_without_on_clauses
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_private_typedef_functions
    - avoid_relative_lib_imports
    - avoid_returning_null
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - avoid_types_on_closure_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - lines_longer_than_80_chars
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - omit_local_variable_types
    - one_member_abstracts
    - package_names
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - slash_for_doc_comments
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_parenthesis
    - unnecessary_statements
    - unrelated_type_equality_checks
    - use_to_and_as_if_applicable
    - valid_regexps
