name: contentful_dart
description: A delightful Dart interface to Contentful's content delivery API.
version: 0.0.1
author: Sasha Prokhorenko <djminikin@gmail.com>
repository: https://github.com/data-hfg/contentful_dart.git
homepage: https://github.com/data-hfg/contentful_dart.git
issue_tracker: https://github.com/data-hfg/contentful_dart/issues

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  built_collection: ^4.2.2
  built_value: ^6.7.0
  http: ^0.12.0+2
  meta: ^1.1.6

dev_dependencies:
  build_runner: ^1.6.5
  built_value_generator: ^6.7.0
  built_value_test: ^6.7.0
  pedantic: ^1.8.0+1
  test: ^1.6.5
  coverage: ^0.13.2
