name: Contentfuly
description: Contentful API client for Dart & Flutter.
version: 0.0.1
author: Sasha Prokhiorenko <djminikin@gmail.com>
repository: https://github.com/data-hfg/contentfuly.git
homepage: https://github.com/data-hfg/contentfuly.git

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  built_collection: ^4.2.2
  built_value: ^6.7.0
  http: ^0.12.0+2

dev_dependencies:
  build_runner: ^1.6.1
  built_value_generator: ^6.7.0
  built_value_test: ^6.7.0