name: contentfuly
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.2.2
  built_value: ^6.7.0
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.1
  built_value_generator: ^6.7.0
  built_value_test: ^6.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: