name: flutter_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  contentful_dart:
    path: ../../
  cupertino_icons: ^0.1.2

flutter:
  uses-material-design: true
