name: contentful_client
description: A delightful Dart interface to Contentful's content delivery API.
version: 0.1.0
repository: https://github.com/amondnet/contentful_client.git
homepage: https://github.com/amondnet/contentful_client/package
issue_tracker: https://github.com/data-hfg/contentful_client/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_collection: ^4.3.0
  built_value: ^7.0.0
  http: ^0.12.1
  meta: ^1.1.8
  http_parser: ^3.0.0
  tuple: ^1.0.0
  http2: ^1.0.0
dev_dependencies:
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  built_value_test: ^7.0.0
  build_test:
  matcher: ^0.12.6
  mockito: ^4.1.1
  pedantic: ^1.9.0
  test_coverage: 0.4.0
  test: ^1.9.4
  angel_framework: ^2.0.0
  cli_repl: ^0.2.0