name: contentful_dart
description: A delightful Dart interface to Contentful's content delivery API.
version: 0.0.5
author: Sasha Prokhorenko <djminikin@gmail.com>
repository: https://github.com/data-hfg/contentful.dart.git
homepage: https://github.com/data-hfg/contentful.dart.git
issue_tracker: https://github.com/data-hfg/contentful.dart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_collection: ^4.3.0
  built_value: ^7.0.0
  http: ^0.12.0+3
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  built_value_test: ^7.0.0
  matcher: ^0.12.6
  mockito: ^4.1.1
  pedantic: ^1.9.0
  test_coverage: 0.4.0
  test: ^1.9.4
