name: contentful_dart
description: A delightful Dart interface to Contentful's content delivery API.
version: 0.0.5
author: Sasha Prokhorenko <djminikin@gmail.com>
repository: https://github.com/data-hfg/contentful.dart.git
homepage: https://github.com/data-hfg/contentful.dart.git
issue_tracker: https://github.com/data-hfg/contentful.dart/issues

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  built_collection: ^4.2.2
  built_value: ^6.7.1
  http: ^0.12.0+2
  meta: ^1.1.7

dev_dependencies:
  build_runner: ^1.6.9
  built_value_generator: ^6.7.1
  built_value_test: ^6.7.1
  matcher: ^0.12.5
  mockito: ^4.1.0
  pedantic: ^1.8.0+1
  test_coverage: 0.3.0+1
  test: ^1.6.9
